# Load DSL and Setup Up Stages
require 'capistrano/setup'

# Includes default deployment tasks
require 'capistrano/deploy'

require 'capistrano/rvm'
require 'capistrano/bundler'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'
require 'capistrano/rails/console'
require "airbrussh/capistrano"
require 'capistrano/passenger'
require 'pry'

require 'yaml'
FileUtils.mkdir_p 'log'
invoke :production
